### ISSUE TITLE
添加管理程序自更新功能

### ISSUE THREAD

**Issue by J-ZhengLi** [J-ZhengLi/custom-rust-dist#115]
程序可联网检查自身更新，并且能替换自身的二进制（在windows上要注意，可能会触发 "当前应用被另一个程序占用" 错误）。

**Comment by LuuuXXX** [comment]
版本更新 需要存储版本信息的OBS服务 以及相关配置文件

**Comment by LuuuXXX** [comment]
使用OBS上传下载需要密钥 建议改成类似rustup的文件存储系统
