### ISSUE TITLE
win管理工具删除·没有删干净

### ISSUE THREAD

**Issue by surechen** [J-ZhengLi/custom-rust-dist#134]
![image](https://github.com/user-attachments/assets/387f4c51-e669-4bfe-a006-ec476b543382)

**Comment by J-ZhengLi** [comment]
这应该是因为卸载时没有关闭图中进程导致的，看上去其它文件都成功删除了，但这个二进制的进程因为被占用所以windows系统无法将其删除。

卸载程序无法检测每个安装的文件都是否被占用，否则复杂度太高了，故无需处理
