### ISSUE TITLE
GUI界面美化

### ISSUE THREAD

**Issue by LuuuXXX** [J-ZhengLi/custom-rust-dist#24]

**Comment by J-ZhengLi** [comment]
1. 按钮布局优化下，改成动态大小，现在是固定大小，换个分辨率就叠在一起了
2.  窗口大小改成可变的
3. 优化组件选择界面，太丑
4. 进度条下面加个安装详细信息的展示界面（textbox）
5. 结束界面加个 <尝试> 按钮

6. （优先级低）最好加个可以显示步骤的侧边栏

**Comment by J-ZhengLi** [comment]
fixed by: #31
