### ISSUE TITLE
安装包需要是一个.exe文件，不应该带packages文件夹

### ISSUE THREAD

**Issue by surechen** [J-ZhengLi/custom-rust-dist#52]
目前带一个packages文件夹：
对于在线版，需要把这个在线拉取
对于离线版，需要跟安装包打到一个.exe中

**Comment by J-ZhengLi** [comment]
如果全部打在一个 exe 中，现版本在windows上有可能会超过3g (msvc+全套rust工具链+vscode)。

尽管这样可行，但是用户在执行的时候操作系统会先将其加载到ram，会造成内存占用过多或者爆内存的情况。并且如果后续我们支持的工具总包超过4g, 就相当于直接放弃了32位操作系统支持
