### ISSUE TITLE
安装目录不能手动输入

### ISSUE THREAD

**Issue by surechen** [J-ZhengLi/custom-rust-dist#53]
这里必须通过选择文件夹按钮来点击，如果手动输入的话，在后面的步骤中，手动输入的文件夹名会丢失

通过选择文件夹按钮选择d盘，之后手动输入了文件夹名
![image](https://github.com/user-attachments/assets/f6ab57ec-b992-4efd-b2ac-e60ef98de731)

文件夹名字丢失
![image](https://github.com/user-attachments/assets/cc6aa3b3-e2bb-4607-96d7-452694198d72)

**Comment by J-ZhengLi** [comment]
已修复
