### ISSUE TITLE
我安装之前手动配置过系统环境变量RUSTUP_HOME和CARGO_HOME，安装发行版后发现没有变更，用户环境变量变更了

### ISSUE THREAD

**Issue by surechen** [J-ZhengLi/custom-rust-dist#56]
![image](https://github.com/user-attachments/assets/cfde6a32-7051-421b-8293-269a3d32066b)
![image](https://github.com/user-attachments/assets/35ce3027-2535-46ea-aea2-7f2609772617)

**Comment by J-ZhengLi** [comment]
工具不修改System变量，只能修改用户环境变量，修改系统变量需要 Admin 权限。

但是用户环境变量读取优先于系统变量，所以不影响.
